### ISSUE TITLE
Bug Cricket

### ISSUE THREAD

**Issue by verygood142** [marpe/XnaDarts#3] opened 2016-12-07 10:13 UTC
hello. it is possible to fix the bug on the cricket?
bug invention cricket.cs row 141

**Comment by marpe** [comment] 2016-12-07 11:57
I am aware of the issue you emailed me about but I have not had time to fix it... since you've been so adamant about it I will try to get to it this weekend ;)

**Comment by verygood142** [comment] 2016-12-08 22:42
Thank you

**Comment by marpe** [comment] 2016-12-10 17:35
I've been trying to reproduce the problem, but I can't figure it out. Can you explain how you ran into this bug?

**Comment by verygood142** [comment] 2016-12-10 18:51
if you connected Arduino with the target you Presenting the bug problem.

1: connect the dartboard with Arduino
2: play with two players to cricket
3: langiare the game with 2 players to cricket
4: playing all the time to wait for the bug

or tried more dartboard and the problem occurs all the time

or tried both Arduino UNO and Arduino Mega, and the problem remains. here is my code



//#include <Keypad.h>
const byte numRows = 16; //number of rows
const byte numCols = 4; //number of columns
const int debounceTime = 100;//20 works better than great !

byte rowPins[numRows] = {22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37};//connect to the row pinouts of the keypad
byte colPins[numCols] = {A0, A1, A2, A3}; //connect to the column pinouts of the keypad
int buttonOutPin = A4; // output to buttons
int buttonInPins[] = {38, 39, 40, 41, 42, 43, 44};



void setup()
{
  Serial.begin(9600);
  Serial.println("Starting up");
  for (int row = 0; row < numRows; row++)
  {
    pinMode(rowPins[row],INPUT);       // Set row pins as input
    digitalWrite(rowPins[row],HIGH);   // turn on Pull-ups
  }
  for (int column = 0; column < numCols; column++)
  {
    pinMode(colPins[column],OUTPUT);     // Set column pins as outputs for writing
    digitalWrite(colPins[column],HIGH);  // Make all columns inactive
  }
  
//button setup
 

  pinMode(buttonOutPin, OUTPUT);
  digitalWrite(buttonOutPin, HIGH);
  
  for(int i = 0; i < 7; i++)
  {
      pinMode(buttonInPins[i], INPUT);
  }
}


void loop()
{


  for(int i = 0; i < 7; i++)
  {
    if(digitalRead(buttonInPins[i]) == HIGH)
    {
      Serial.print("B: ");
      Serial.print(i);
      Serial.println("");
      delay(200);
    
    }


for(int column = 0; column < numCols; column++)
  {
    digitalWrite(colPins[column],LOW);         // Activate the current column.
    for(int row = 0; row < numRows; row++)     // Scan all rows for a key press
    {
      if(digitalRead(rowPins[row]) == LOW)     // Is a key pressed?
      {
        delay(debounceTime);                   // debounce
        while(digitalRead(rowPins[row]) == LOW);  // wait for key to be released
        Serial.print("H: ");
        Serial.print(row);
        Serial.print(", ");
        Serial.print(column);
        Serial.println("");
        delay(50);
      }
    }
    digitalWrite(colPins[column],HIGH);     // De-activate the current column.
  }
}
}

**Comment by marpe** [comment] 2016-12-10 21:21
Alright, I will try again to reproduce it. Thanks for the info.

**Comment by verygood142** [comment] 2016-12-12 08:57
thanks to you for your time

**Comment by verygood142** [comment] 2016-12-14 18:50
hello, I Found a bug?

**Comment by verygood142** [comment] 2016-12-19 17:01
hello, new on the cricket bug? 6 games of 10 should be continually crash

**Comment by verygood142** [comment] 2016-12-19 17:03
I tested the old versions work properly except for versions 0.2.0

**Comment by marpe** [comment] 2016-12-19 20:11
Hmm, ok I was trying to recreate the bug this weekend but could not do so. Will try again as soon as I have more free time.

I did some work on getting some resolution issues resolved as well since the UI does not look very appealing in lower resolutions.

Really appreciate the time you spend to help me out with this, wish I could spend more time fixing these issues.

**Comment by verygood142** [comment] 2016-12-20 13:43
ok, I hope you solve this problem. I tried in every way, but without success. thank you

**Comment by verygood142** [comment] 2017-01-23 08:27
hello, I wanted information on the cricket bug. You Can Solve the bug?

**Comment by marpe** [comment] 2017-01-26 22:01
I've played maybe 20 games of cricket today and I have not encountered the bug so far. I'm pretty sure I have not made any significant changes to the cricket code since the latest release but I put up a new one built with the Monogame framework instead of Xna: https://github.com/marpe/XnaDarts/releases/tag/0.3.0 . Download it, copy over your options.bin file and try it out.

**Comment by verygood142** [comment] 2017-01-31 15:08
hello, also tried this version, and the bug there forever.
I attach a dove demonstrate a connection Video of the collapse

https://www.dropbox.com/sh/otm2t0bd7lfy7ml/AAC2iRClj3sxOygzgod-FzlUa?dl=0

**Comment by verygood142** [comment] 2017-01-31 15:09
cricket of version 0.1.0 works perfectly

**Comment by marpe** [comment] 2017-02-03 23:16
Ah, I've watched the video and it gave me a few ideas of what might be the cause. Thank you so much for taking the time to record it and I feel really sorry for causing any frustration and that it has taken me this long to figure out.

**Comment by verygood142** [comment] 2017-02-04 00:23
Finally with the video is all over the chia ro bug That The Game.
the videos are fast enough in being able to visionere the bug,
but in Real Play with friends, go the bug Often the first usually match the sixteenth lap / 18

**Comment by marpe** [comment] 2017-02-04 00:35
I think I've finally been able to identify the issue!

It because a dart is registered at the same time as the score is calculated. I didn't realize that the event which is fired when a dart hits the board were running in a separate thread! Which also means that this bug is only encountered when running with a connected dart board.

I've been developing the application without the dart board connected and inputting the hits using the control displayed by hitting the F6 key, which is why I was not able to replicate the bug before.

Finally dusted off the dart board, fixed a few soldering connections and plugged it in and the bug occurred within minutes.

**Comment by marpe** [comment] 2017-02-04 04:44
Ok I think the commit I references above takes care of the bug, but I have made a lot of other changes so I will need some more time before I can put up a new release. I've been working on master out and fixes for the user interface in different resolutions as well :) Hopefully I can get more work done later this weekend!

**Comment by verygood142** [comment] 2017-02-06 19:05
ok thanks for your work on the fix the bug, but it was becoming too annoying, in fact, with The Friends we play no more fin WHEN ARE not Fixed the problem. we are always waiting for the master out :-)

we look forward to a new version with bug  and arranged master out :-)

Thanks for your time.

**Comment by marpe** [comment] 2017-02-08 00:39
I put up a release candidate: https://github.com/marpe/XnaDarts/releases . I know there's still an issue navigating the menu with the mouse which I will fix before a final release, but I figured that you would want to check if the crash has been fixed and try master out. I would be surprised If I got it right on the first try, there are probably still lots of bugs to iron out.

**Comment by marpe** [comment] 2017-02-08 00:42
Took me one second to find a bug. Changing to master out if you're at 1 point will mess up your score 😢

**Comment by marpe** [comment] 2017-02-08 06:36
Uploaded a new release which fixes another zero one related bug: https://github.com/marpe/XnaDarts/releases/tag/0.3.1-rc.2

**Comment by verygood142** [comment] 2017-02-08 06:44
I'm testing the masterOut and I must say what a wonderful the output of this version.
Now I try 0.3.1 Release Candidate 2.
and you can ADD to start scoring opening with 2 multiplier?

**Comment by marpe** [comment] 2017-02-08 07:01
I'm not sure I understand your question. If it's Master **In** you mean, I will add it in a later release

**Comment by verygood142** [comment] 2017-02-08 07:22
I tested the 0.3.1 Release Candidate 2, and the bug still be there.
WHEN The first player CLOSES, and the Second player goes bust, the game does not CLOSE.

sorry for my English :-)
I mean if you could ADD master in

**Comment by verygood142** [comment] 2017-02-09 07:26
I tried the cricket and LOOKS Get Well bug finally :-)
It needs to fix the bug on masterOut and if possible to implement the master In.
one last thing I would like to know, BEGINNING of the first round by throwing the dart, MUST Wait What disappears the written round.  Is there a way to PULL the dart and vanish away the written round?

**Comment by verygood142** [comment] 2017-02-14 07:59
hello, Found A Solution on the bug bust masterOut?
We would like to implement if possible before closing Councils.
I'll explain, implement on the screen of the dove Tips table PULL the dart to be able CLOSE in masterOut. it would be possible :-)

**Comment by marpe** [comment] 2017-02-15 10:10
Hi,

I have not had time to work on it yet, but I will try to get it done as
soon as I can.

I'm not sure what you mean by "We would like to implement if possible
before closing Councils. I'll explain, implement on the screen of the dove
Tips table PULL the dart to be able CLOSE in masterOut. it would be
possible :-)"

Do you mean tips on how to finish? For example, if you're on 155, it would
say "T20 T19 D19" at the top of the screen?

**Comment by verygood142** [comment] 2017-02-15 11:49
Yes, right. and you can turn tips?

**Comment by verygood142** [comment] 2017-02-15 20:42
remove the written round the first launch of the dart. it is annoying :-)

**Comment by verygood142** [comment] 2017-03-01 21:14
Hi how are you? and you can fix the bug on masterOut?
I recommend if you can add the master In and tips on how to finish. For example, if you are on 155, would
say "T20 T19 D19" in the top of the screen?

**Comment by marpe** [comment] 2017-03-04 16:59
I'm closing this since the cricket bug seems to be resolved. Please open separate issues for any feature requests or other bugs.

**Closed by marpe** 2017-03-04 16:59 UTC
Labels: bug
